config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

    resources :clinics do
      member do
      post :create_doctor
    end
      resources :patients
    end
    resources :medications

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base

  has_many :patients, dependent: :destroy
  has_many :doctors, as: :doctorable

  US_STATE_OPTIONS =
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :doctorable, polymorphic: true
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :patient_medications
  has_many :patients, through: :patient_medications
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :clinic
  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_many :doctors, as: :doctorable

  BLOOD_TYPE_OPTIONS = [
    ["O-", "O-"],
    ["O+", "O+"],
    ["A-", "A-"],
    ["A+", "A+"],
    ["B-", "B-"],
    ["B+", "B+"],
    ["AB-", "AB-"],
    ["AB+", "AB+"],
  ]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :gender, presence: true
  validates :blood_type, presence: true
  validate :at_least_10
  def at_least_10
    if self.date_of_birth
        errors.add(:date_of_birth, 'Error. Patient must be at least 10 years old') if self.date_of_birth > 10.years.ago.to_date  
    end
  end



end


# validate :at_least_18

# def at_least_18

#     if self.birthdate
#       errors.add(:birthdate, 'You must be 18 years or older.') if self.birthdate > 18.years.ago.to_date
#     end
# end

app/models/patient_medication.rb
class PatientMedication < ActiveRecord::Base
  belongs_to :patient
  belongs_to :medication

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  def index
    @clinics = Clinic.all
  end

  def show
    set_clinic
    @patients = @clinic.patients
    @doctor = Doctor.new
  end
  
  def new
    @clinic = Clinic.new
  end

  def create
    @clinic = Clinic.create my_params
    redirect_to clinics_path
  end

  def edit
    @clinic = Clinic.find params[:id]
  end

  def update
    @clinic = Clinic.find params[:id]
    @clinic.update my_params
    redirect_to clinics_path
  end

  def destroy
    @clinic = Clinic.find params[:id]
    @clinic.destroy
    redirect_to clinics_path
  end

  def create_doctor
    @clinic = Clinic.find params[:id]
    @doctor = @clinic.doctors.create doctor_params
    redirect_to clinic_path(@clinic)
  end

private
  def my_params
    params.require(:clinic).permit(
      :name,
      :st_address,
      :city,
      :state
    )
  end

  def set_clinic
    @clinic = Clinic.find params[:id]
  end

  def doctor_params
    params.require(:doctor).permit(
      :doctor_name
      )
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

  def index
    @medications = Medication.all
  end

  def show
    @medication = Medication.find params[:id]
    @patients = @medication.patients
  end

    # @clinic = Clinic.find params[:clinic_id]
    # @patient = @clinic.patients.find params[:patient_id]
    # @medication = @patient.medications.new


  def new
    @medication = Medication.new
    @patients = Patient.all
  end

  def create
    @medication = Medication.create medication_params
    redirect_to medications_path
  end

  def edit
    @medication = Medication.find params[:id]
    @patients = Patient.all
  end

  def update
    @medication = Medication.find params[:id]
    @medication.update medication_params
    redirect_to medications_path
  end

  def destroy
    @medication = Medication.find params[:id]
    @medication.delete
    redirect_to medications_path
  end


private
  def medication_params
    params.require(:medication).permit(
      :name,
      :company,
      :adverse_reactions,
      :generic_option,
      patient_ids: []
      )
  end

  def set_patient
    @patient = Patient.find params[:id]
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
   @clinic = Clinic.find params[:clinic_id]
   @patient = Patient.find params[:id]
   @medications = @patient.medications
  end


  def new
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.new
    @medications = Medication.all
  end

  def create
    @clinic = Clinic.find params[:clinic_id]
    @medications = Medication.all
    @patient = @clinic.patients.create patient_params
    if @clinic.patients.create
      flash[:notice] = 'Patient info was successfully saved.'
      redirect_to clinic_path(@clinic)
    else
      flash[:error] = 'Patient info was NOT successfully saved.'
      render :new
    end
  end

  def edit
    @clinic = Clinic.find params[:clinic_id]
    @medications = Medication.all
    @patient = @clinic.patients.find params[:id]
  end

  def update
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    if @patient.update_attributes patient_params
      flash[:notice] = 'Patient info was successfully updated.'
      redirect_to clinic_path(@clinic)
    else
      flash[:notice] = 'Patient info was NOT successfully updated.'
      render :edit
    end

  end

  def destroy
    @patient = Patient.find params[:id]
    @clinic = Clinic.find params[:clinic_id]
    if @patient.destroy
      flash[:notice] = 'Patient info was successfully deleted.'
      redirect_to clinic_path(@clinic)
    else
      flash[:notice] = 'Patient info was NOT successfully deleted.'
    end
  end


private
  def patient_params
    params.require(:patient).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :description,
        :gender,
        :blood_type,
        medication_ids: []
      ) 
  end

  def set_clinic
    @clinic = Clinic.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/clinics/_form.html.erb
<%= form_for @clinic do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :st_address %>
  <%= f.text_field :st_address %>
  <br>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br>
  <%= f.label :state %>
  <%= f.select :state, options_for_select(Clinic::US_STATE_OPTIONS, f.object.state), include_blank: "----Select State___" %>
  <br>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "Cancel and Return to Clinics", clinics_path %>

app/views/clinics/edit.html.erb
<h1><strong>Edit Clinic Information</strong></h1>

<%= render 'form' %>

app/views/clinics/index.html.erb
<h1><strong>Clinics</strong></h1>

<%= link_to "Add New Clinic", new_clinic_path %>
<br>
<%= link_to "Return to Main", root_path %>
<br>
<ul>
  <% @clinics.each do |clinic| %>
    <li>
      <strong>Clinic Name:</strong>
      <%= link_to clinic.name, clinic_path(clinic) %>
      <br>
      <strong>Street Address:</strong>
      <%= clinic.st_address %>
      <br>
      <strong>City:</strong>
      <%= clinic.city %>
      <br>
      <strong>State:</strong>
      <%= clinic.state %>
    </li>
    <%= link_to "Edit Clinic", edit_clinic_path(clinic) %>
    |
    <%= link_to "Delete Clinic", clinic_path(clinic), method: :delete %>
    <br>
    <br>
  <% end %>
</ul>

app/views/clinics/new.html.erb
<h1><strong>Add Information for New Clinic</strong></h1>

<%= render 'form' %>

app/views/clinics/show.html.erb
<strong> <h1>Clinic Info: </h1></strong>
<strong>Clinic Name:</strong>
<%= @clinic.name %>
<br>
<strong>Street Address:</strong>
<%= @clinic.st_address %>
<br>
<strong>City:</strong>
<%= @clinic.city %>
<br>
<strong>State:</strong>
<%= @clinic.state %>
<br>
<%= link_to "Edit Clinic", edit_clinic_path(@clinic) %>
|
<%= link_to "Delete Clinic", clinic_path(@clinic), method: :delete %>
<br>
<%= link_to "Return to Clinics", clinics_path %>
|
<%= link_to "Return to Main", root_path %>
<br>
<br>
<p>
  <strong>Patient List:</strong>
  <%= link_to "Add Patient", new_clinic_patient_path(@clinic) %>
  <br>
  <% @patients.each do |patient| %>
    <li>
      <strong>Name:</strong>
      <%= link_to patient.last_name + ", " + patient.first_name, clinic_patient_path(@clinic, patient) %>
      <br>
      <strong>Date of Birth:</strong>
      <%= patient.date_of_birth %>
      <br>
      <strong>Description:</strong>
      <%= patient.description %>
      <br>
      <strong>Gender:</strong>
      <%= patient.gender %>
      <br>
      <strong>Blood Type:</strong>
      <%= patient.blood_type %>
      <br>
      <%= link_to "Edit Patient Information", edit_clinic_patient_path(@clinic, patient) %>
      |
      <%= link_to "Delete Patient Information", clinic_patient_path(@clinic, patient), method: :delete %>
    </li>
    <br>
  <% end %>
</p>
<strong>Clinic Doctors:</strong>
<br>
<ul>
  <% @clinic.doctors.each do |doctor| %>
    <li>
      <%= doctor.doctor_name %>
      <br>
    </li>
  <% end %>
</ul>
<%= form_for @doctor, url: create_doctor_clinic_path(@clinic) do |f| %>
  <%= f.label :doctor_name %>
  <%= f.text_area :doctor_name %>
  <br>
  <%= f.submit %>
<% end %>

app/views/home/index.html.haml
%h1 Welcome To The Hospital Tracking System
%br
= link_to "Go To Clinics Information", clinics_path
%br
= link_to "Go to Medication Information", medications_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HwDay12Assignment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/medications/_form.html.erb
<%= form_for [@medication] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :company %>
  <%= f.text_field :company %>
  <br>
  <%= f.label :adverse_reactions %>
  <%= f.text_area :adverse_reactions %>
  <br>
  <%= f.label :generic_option %>
  <%= f.radio_button(:generic_option, 1) %>
  <%= f.label(:generic_option, "yes") %>
  <%= f.radio_button(:generic_option, 0) %>
  <%= f.label(:generic_option, "no") %>
  <br>

  <br>
  <% @patients.each do |patient| %>
    <%= check_box_tag 'medication[patient_ids][]', patient.id, @medication.patients.include?(patient) %>
    <%= patient.last_name %>
    <br>
 <% end %>
  <br>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "Cancel", medications_path %>
|
<%= link_to "Return to Main", root_path %>

app/views/medications/edit.html.erb
<h1><strong>Edit Medication</strong></h1>

<%= render 'form' %>

app/views/medications/index.html.erb
<h1>Medications Info</h1>

<%= link_to "Create a New Medication", new_medication_path %>
<br>
<ul>
  <% @medications.each do |medication| %>
    <li>
      <strong>Medication Name:</strong>
      <%= link_to medication.name, medication_path(medication) %>
      <br>
      <strong>Company:</strong>
      <%= medication.company %>
      <br>
      <strong>Adverse Reactions:</strong>
      <%= medication.adverse_reactions %>
      <br>
      <strong>Generic Options Available:</strong>
      <%= medication.generic_option %>

      <br>
   <%= link_to "Edit Medication", edit_medication_path(medication) %>
   |
   <%= link_to "Delete Medication", medication_path(medication), method: :delete %>
   </li>
   <br>
    <% end %>
</ul>
<%= link_to "Return to Main", root_path %>

app/views/medications/new.html.erb
<strong><h1>Add a Medication</h1></strong>

<%= render 'form' %>

app/views/medications/show.html.erb
<h1>Medication Info </h1>


<strong>Medication Name:</strong>
<%= @medication.name %>
<br>
<strong>Company:</strong>
<%= @medication.company %>
<br>
<strong>Adverse Reactions:</strong>
<%= @medication.adverse_reactions %>
<br>
<strong>Generic Options Available:</strong>
<%= @medication.generic_option %>
<br>
<strong>Patient Names:</strong>
<br>
<% @patients.each do |patient| %>
  <%= patient.last_name %>
  <%= patient.first_name %>
  <br>
<% end %>



<%= link_to "Edit Medication", edit_medication_path(@medication) %>
|
<%= link_to "Delete Medication",  medication_path(@medication), method: :delete %>
<br>
<%= link_to "Return to Medications", medications_path %>
|
<%= link_to "Return to Main", root_path %>

app/views/patients/_form.html.haml
= form_for([@clinic, @patient]) do |f|
  - if @patient.errors.any?
    %p#notice= notice
    - @patient.errors.full_messages.each do |message|
      = message
      %br/
%br/
= form_for [@clinic, @patient] do |f|
  %strong= f.label :first_name
  = f.text_field :first_name
  %br/
  %strong= f.label :last_name
  = f.text_field :last_name
  %br/
  %strong= f.label :date_of_birth
  = f.date_select :date_of_birth, :start_year => Date.today.year - 110, :end_year => Date.today.year
  %br/
  %strong= f.label :description
  = f.text_field :description
  %br/
  %strong= f.label :gender
  = f.radio_button(:gender, "male")
  = f.label(:gender, "male")
  = f.radio_button(:gender, "female")
  = f.label(:gender, "female")
  %br/
  %strong= f.label :blood_type
  = f.select :blood_type, options_for_select(Patient::BLOOD_TYPE_OPTIONS, f.object.blood_type), include_blank: "---Select---"
  %br/
  - @medications.each do |medication|
    = check_box_tag 'patient[medication_ids][]', medication.id, @patient.medications.include?(medication)
    = medication.name
  %br/
  = f.submit
= link_to "Cancel", clinic_path(@clinic)
= link_to "Return to Main", root_path

app/views/patients/edit.html.erb
<h1>Edit Patient Info</h1>
<%= render 'form' %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Patients</h1>
<br>
<%= link_to "Create New Patient Information", new_patient_path %>
<br>
<ul>
<% @patients.each do |patient| %>
  <li>
    <strong>Patient Name:</strong>
    <%= link_to patient.last_name + ", " + patient.first_name, patient_path(patient) %>
    <br>
    <strong>DOB:</strong>
    <%= patient.date_of_birth %>
    <br>
    <strong>Description:</strong>
    <%= patient.description %>
    <br>
    <strong>Gender:</strong>
    <%= patient.gender %>
    <br>
    <strong>Blood Type:</strong>
    <%= patient.blood_type %>
    <br>
    <%= link_to "Edit Patient", edit_patient_path(patient) %>
    |
    <%= link_to "Delete Patient", patient_path(patient), method: :delete %>
  </li>
  <br>
<% end %>
</ul>
<%= link_to "Return to Main", root_path %>

app/views/patients/new.html.erb
<h1>Enter Patient Information</h1>

<%= render 'form' %>

app/views/patients/show.html.erb
<strong>Information for:</strong>
<br>
<strong>Patient:</strong> <%= @patient.last_name + ", " + @patient.first_name %>
<br>
<strong>Patient DOB:</strong>
<%= @patient.date_of_birth %>
<br>
<strong>Patient Illness Description:</strong>
<%= @patient.description %>
<br>
<strong>Patient Gender:</strong>
<%= @patient.gender %>
<br>
<strong>Patient Blood Type:</strong>
<%= @patient.blood_type %> 
<br>
<%= link_to "Edit Patient/Medication", edit_clinic_patient_path(@clinic, @patient) %>
|
<%= link_to "Delete Patient", clinic_patient_path(@clinic, @patient), method: :delete %>
<br>
<%= link_to "Return to Clinic", clinic_path(@clinic) %>
|
<%= link_to "Return to Main", root_path %>
<br>
<br>
<strong>Patient Medications:</strong>
<br>
<ul>
  <% @medications.each do |medication| %>
    <li>
      <strong>Medication Name:</strong>
      <%= medication.name %>
      <br>
      <strong>Company:</strong>
      <%= medication.company %>
      <br>
      <strong>Adverse Reactions:</strong>
      <%= medication.adverse_reactions %>
      <br>
      <strong>Generic Options Available:</strong>
      <%= medication.generic_option %>
      <br>
    <br>
    <br>
    </li>
  <% end %>